// flow-typed signature: 3fb978c16bb9546732f8c3dea8285ab0
// flow-typed version: <<STUB>>/electron-require_v^0.3.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-require/tests/app/main/index' {
  declare module.exports: any;
}

declare module 'electron-require/tests/app/main/module' {
  declare module.exports: any;
}

declare module 'electron-require/tests/app/renderer/index' {
  declare module.exports: any;
}

declare module 'electron-require/tests/app/renderer/module' {
  declare module.exports: any;
}

declare module 'electron-require/tests/custom/module' {
  declare module.exports: any;
}

declare module 'electron-require/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-require/index' {
  declare module.exports: $Exports<'electron-require'>;
}
declare module 'electron-require/index.js' {
  declare module.exports: $Exports<'electron-require'>;
}
declare module 'electron-require/tests/app/main/index.js' {
  declare module.exports: $Exports<'electron-require/tests/app/main/index'>;
}
declare module 'electron-require/tests/app/main/module.js' {
  declare module.exports: $Exports<'electron-require/tests/app/main/module'>;
}
declare module 'electron-require/tests/app/renderer/index.js' {
  declare module.exports: $Exports<'electron-require/tests/app/renderer/index'>;
}
declare module 'electron-require/tests/app/renderer/module.js' {
  declare module.exports: $Exports<'electron-require/tests/app/renderer/module'>;
}
declare module 'electron-require/tests/custom/module.js' {
  declare module.exports: $Exports<'electron-require/tests/custom/module'>;
}
declare module 'electron-require/tests/tests.js' {
  declare module.exports: $Exports<'electron-require/tests/tests'>;
}
