// flow-typed signature: cd36efa280df6b2c279a08375b4c9732
// flow-typed version: <<STUB>>/electron-remote_v^1.0.8/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-remote'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-remote' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-remote/lib/custom-operators' {
  declare module.exports: any;
}

declare module 'electron-remote/lib/execute-js-func' {
  declare module.exports: any;
}

declare module 'electron-remote/lib/index' {
  declare module.exports: any;
}

declare module 'electron-remote/lib/remote-ajax' {
  declare module.exports: any;
}

declare module 'electron-remote/lib/remote-event-browser' {
  declare module.exports: any;
}

declare module 'electron-remote/lib/remote-event' {
  declare module.exports: any;
}

declare module 'electron-remote/lib/renderer-require-preload' {
  declare module.exports: any;
}

declare module 'electron-remote/lib/renderer-require' {
  declare module.exports: any;
}

declare module 'electron-remote/lib/rx-dom' {
  declare module.exports: any;
}

declare module 'electron-remote/remote-ajax' {
  declare module.exports: any;
}

declare module 'electron-remote/src/custom-operators' {
  declare module.exports: any;
}

declare module 'electron-remote/src/execute-js-func' {
  declare module.exports: any;
}

declare module 'electron-remote/src/index' {
  declare module.exports: any;
}

declare module 'electron-remote/src/remote-ajax' {
  declare module.exports: any;
}

declare module 'electron-remote/src/remote-event-browser' {
  declare module.exports: any;
}

declare module 'electron-remote/src/remote-event' {
  declare module.exports: any;
}

declare module 'electron-remote/src/renderer-require-preload' {
  declare module.exports: any;
}

declare module 'electron-remote/src/renderer-require' {
  declare module.exports: any;
}

declare module 'electron-remote/src/rx-dom' {
  declare module.exports: any;
}

declare module 'electron-remote/test/asserttest' {
  declare module.exports: any;
}

declare module 'electron-remote/test/dummy-module' {
  declare module.exports: any;
}

declare module 'electron-remote/test/recursive-proxy-handler' {
  declare module.exports: any;
}

declare module 'electron-remote/test/remote-event' {
  declare module.exports: any;
}

declare module 'electron-remote/test/renderer-require' {
  declare module.exports: any;
}

declare module 'electron-remote/test/support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-remote/lib/custom-operators.js' {
  declare module.exports: $Exports<'electron-remote/lib/custom-operators'>;
}
declare module 'electron-remote/lib/execute-js-func.js' {
  declare module.exports: $Exports<'electron-remote/lib/execute-js-func'>;
}
declare module 'electron-remote/lib/index.js' {
  declare module.exports: $Exports<'electron-remote/lib/index'>;
}
declare module 'electron-remote/lib/remote-ajax.js' {
  declare module.exports: $Exports<'electron-remote/lib/remote-ajax'>;
}
declare module 'electron-remote/lib/remote-event-browser.js' {
  declare module.exports: $Exports<'electron-remote/lib/remote-event-browser'>;
}
declare module 'electron-remote/lib/remote-event.js' {
  declare module.exports: $Exports<'electron-remote/lib/remote-event'>;
}
declare module 'electron-remote/lib/renderer-require-preload.js' {
  declare module.exports: $Exports<'electron-remote/lib/renderer-require-preload'>;
}
declare module 'electron-remote/lib/renderer-require.js' {
  declare module.exports: $Exports<'electron-remote/lib/renderer-require'>;
}
declare module 'electron-remote/lib/rx-dom.js' {
  declare module.exports: $Exports<'electron-remote/lib/rx-dom'>;
}
declare module 'electron-remote/remote-ajax.js' {
  declare module.exports: $Exports<'electron-remote/remote-ajax'>;
}
declare module 'electron-remote/src/custom-operators.js' {
  declare module.exports: $Exports<'electron-remote/src/custom-operators'>;
}
declare module 'electron-remote/src/execute-js-func.js' {
  declare module.exports: $Exports<'electron-remote/src/execute-js-func'>;
}
declare module 'electron-remote/src/index.js' {
  declare module.exports: $Exports<'electron-remote/src/index'>;
}
declare module 'electron-remote/src/remote-ajax.js' {
  declare module.exports: $Exports<'electron-remote/src/remote-ajax'>;
}
declare module 'electron-remote/src/remote-event-browser.js' {
  declare module.exports: $Exports<'electron-remote/src/remote-event-browser'>;
}
declare module 'electron-remote/src/remote-event.js' {
  declare module.exports: $Exports<'electron-remote/src/remote-event'>;
}
declare module 'electron-remote/src/renderer-require-preload.js' {
  declare module.exports: $Exports<'electron-remote/src/renderer-require-preload'>;
}
declare module 'electron-remote/src/renderer-require.js' {
  declare module.exports: $Exports<'electron-remote/src/renderer-require'>;
}
declare module 'electron-remote/src/rx-dom.js' {
  declare module.exports: $Exports<'electron-remote/src/rx-dom'>;
}
declare module 'electron-remote/test/asserttest.js' {
  declare module.exports: $Exports<'electron-remote/test/asserttest'>;
}
declare module 'electron-remote/test/dummy-module.js' {
  declare module.exports: $Exports<'electron-remote/test/dummy-module'>;
}
declare module 'electron-remote/test/recursive-proxy-handler.js' {
  declare module.exports: $Exports<'electron-remote/test/recursive-proxy-handler'>;
}
declare module 'electron-remote/test/remote-event.js' {
  declare module.exports: $Exports<'electron-remote/test/remote-event'>;
}
declare module 'electron-remote/test/renderer-require.js' {
  declare module.exports: $Exports<'electron-remote/test/renderer-require'>;
}
declare module 'electron-remote/test/support.js' {
  declare module.exports: $Exports<'electron-remote/test/support'>;
}
