// flow-typed signature: bb332ad9d407a47ec774eb038e3a995a
// flow-typed version: <<STUB>>/mobx-store_v^3.4.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-store' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-store/file' {
  declare module.exports: any;
}

declare module 'mobx-store/lib/file' {
  declare module.exports: any;
}

declare module 'mobx-store/lib/filesync' {
  declare module.exports: any;
}

declare module 'mobx-store/lib/index' {
  declare module.exports: any;
}

declare module 'mobx-store/lib/localstorage' {
  declare module.exports: any;
}

declare module 'mobx-store/lib/lodash' {
  declare module.exports: any;
}

declare module 'mobx-store/lib/types' {
  declare module.exports: any;
}

declare module 'mobx-store/lib/util' {
  declare module.exports: any;
}

declare module 'mobx-store/localstorage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-store/file.js' {
  declare module.exports: $Exports<'mobx-store/file'>;
}
declare module 'mobx-store/lib/file.js' {
  declare module.exports: $Exports<'mobx-store/lib/file'>;
}
declare module 'mobx-store/lib/filesync.js' {
  declare module.exports: $Exports<'mobx-store/lib/filesync'>;
}
declare module 'mobx-store/lib/index.js' {
  declare module.exports: $Exports<'mobx-store/lib/index'>;
}
declare module 'mobx-store/lib/localstorage.js' {
  declare module.exports: $Exports<'mobx-store/lib/localstorage'>;
}
declare module 'mobx-store/lib/lodash.js' {
  declare module.exports: $Exports<'mobx-store/lib/lodash'>;
}
declare module 'mobx-store/lib/types.js' {
  declare module.exports: $Exports<'mobx-store/lib/types'>;
}
declare module 'mobx-store/lib/util.js' {
  declare module.exports: $Exports<'mobx-store/lib/util'>;
}
declare module 'mobx-store/localstorage.js' {
  declare module.exports: $Exports<'mobx-store/localstorage'>;
}
