// flow-typed signature: 3abfde995d323fa4536a1e90d3b5f103
// flow-typed version: <<STUB>>/react-tunnel_v^0.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tunnel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tunnel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tunnel/dist/react-tunnel' {
  declare module.exports: any;
}

declare module 'react-tunnel/dist/react-tunnel.min' {
  declare module.exports: any;
}

declare module 'react-tunnel/lib/components/createAll' {
  declare module.exports: any;
}

declare module 'react-tunnel/lib/components/createInject' {
  declare module.exports: any;
}

declare module 'react-tunnel/lib/components/createProvider' {
  declare module.exports: any;
}

declare module 'react-tunnel/lib/index' {
  declare module.exports: any;
}

declare module 'react-tunnel/lib/native' {
  declare module.exports: any;
}

declare module 'react-tunnel/lib/utils/hasEmptyIntersection' {
  declare module.exports: any;
}

declare module 'react-tunnel/lib/utils/isPlainObject' {
  declare module.exports: any;
}

declare module 'react-tunnel/lib/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-tunnel/lib/utils/sharedKeys' {
  declare module.exports: any;
}

declare module 'react-tunnel/native' {
  declare module.exports: any;
}

declare module 'react-tunnel/test/components/inject.spec' {
  declare module.exports: any;
}

declare module 'react-tunnel/test/components/jsdomReact' {
  declare module.exports: any;
}

declare module 'react-tunnel/test/components/Provider.spec' {
  declare module.exports: any;
}

declare module 'react-tunnel/test/utils/hasEmptyIntersection.spec' {
  declare module.exports: any;
}

declare module 'react-tunnel/test/utils/isPlainObject.spec' {
  declare module.exports: any;
}

declare module 'react-tunnel/test/utils/shallowEqual.spec' {
  declare module.exports: any;
}

declare module 'react-tunnel/test/utils/sharedKeys.spec' {
  declare module.exports: any;
}

declare module 'react-tunnel/webpack.config.base' {
  declare module.exports: any;
}

declare module 'react-tunnel/webpack.config.development' {
  declare module.exports: any;
}

declare module 'react-tunnel/webpack.config.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tunnel/dist/react-tunnel.js' {
  declare module.exports: $Exports<'react-tunnel/dist/react-tunnel'>;
}
declare module 'react-tunnel/dist/react-tunnel.min.js' {
  declare module.exports: $Exports<'react-tunnel/dist/react-tunnel.min'>;
}
declare module 'react-tunnel/lib/components/createAll.js' {
  declare module.exports: $Exports<'react-tunnel/lib/components/createAll'>;
}
declare module 'react-tunnel/lib/components/createInject.js' {
  declare module.exports: $Exports<'react-tunnel/lib/components/createInject'>;
}
declare module 'react-tunnel/lib/components/createProvider.js' {
  declare module.exports: $Exports<'react-tunnel/lib/components/createProvider'>;
}
declare module 'react-tunnel/lib/index.js' {
  declare module.exports: $Exports<'react-tunnel/lib/index'>;
}
declare module 'react-tunnel/lib/native.js' {
  declare module.exports: $Exports<'react-tunnel/lib/native'>;
}
declare module 'react-tunnel/lib/utils/hasEmptyIntersection.js' {
  declare module.exports: $Exports<'react-tunnel/lib/utils/hasEmptyIntersection'>;
}
declare module 'react-tunnel/lib/utils/isPlainObject.js' {
  declare module.exports: $Exports<'react-tunnel/lib/utils/isPlainObject'>;
}
declare module 'react-tunnel/lib/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-tunnel/lib/utils/shallowEqual'>;
}
declare module 'react-tunnel/lib/utils/sharedKeys.js' {
  declare module.exports: $Exports<'react-tunnel/lib/utils/sharedKeys'>;
}
declare module 'react-tunnel/native.js' {
  declare module.exports: $Exports<'react-tunnel/native'>;
}
declare module 'react-tunnel/test/components/inject.spec.js' {
  declare module.exports: $Exports<'react-tunnel/test/components/inject.spec'>;
}
declare module 'react-tunnel/test/components/jsdomReact.js' {
  declare module.exports: $Exports<'react-tunnel/test/components/jsdomReact'>;
}
declare module 'react-tunnel/test/components/Provider.spec.js' {
  declare module.exports: $Exports<'react-tunnel/test/components/Provider.spec'>;
}
declare module 'react-tunnel/test/utils/hasEmptyIntersection.spec.js' {
  declare module.exports: $Exports<'react-tunnel/test/utils/hasEmptyIntersection.spec'>;
}
declare module 'react-tunnel/test/utils/isPlainObject.spec.js' {
  declare module.exports: $Exports<'react-tunnel/test/utils/isPlainObject.spec'>;
}
declare module 'react-tunnel/test/utils/shallowEqual.spec.js' {
  declare module.exports: $Exports<'react-tunnel/test/utils/shallowEqual.spec'>;
}
declare module 'react-tunnel/test/utils/sharedKeys.spec.js' {
  declare module.exports: $Exports<'react-tunnel/test/utils/sharedKeys.spec'>;
}
declare module 'react-tunnel/webpack.config.base.js' {
  declare module.exports: $Exports<'react-tunnel/webpack.config.base'>;
}
declare module 'react-tunnel/webpack.config.development.js' {
  declare module.exports: $Exports<'react-tunnel/webpack.config.development'>;
}
declare module 'react-tunnel/webpack.config.production.js' {
  declare module.exports: $Exports<'react-tunnel/webpack.config.production'>;
}
